export default {
  // Queues
  EMAIL_QUEUE: 'EMAIL_QUEUE',
  WEBHOOK_QUEUE: 'WEBHOOK_QUEUE',

  // Job Names
  SEND_EMAIL: 'SEND_EMAIL',

  // Job Types - Email (Sub-types passed in payload)
  SEND_CREDENTIALS: 'SEND_CREDENTIALS',
  SEND_WELCOME: 'SEND_WELCOME',
  SEND_VERIFICATION: 'SEND_VERIFICATION',
  SEND_PASSWORD_RESET: 'SEND_PASSWORD_RESET',
  SEND_INVITE: 'SEND_INVITE',
  SEND_ADMIN_NOTIFICATION: 'SEND_ADMIN_NOTIFICATION',

  // Job Types - Webhooks
  PROCESS_PAYSTACK_WEBHOOK: 'PROCESS_PAYSTACK_WEBHOOK',
  PROCESS_FLUTTERWAVE_WEBHOOK: 'PROCESS_FLUTTERWAVE_WEBHOOK',
};
