export default {
  // Queues
  EMAIL_QUEUE: 'EMAIL_QUEUE',

  // Job Names
  SEND_EMAIL: 'SEND_EMAIL',

  // Job Types - Email (Sub-types passed in payload)
  SEND_WELCOME: 'SEND_WELCOME',
  SEND_VERIFICATION: 'SEND_VERIFICATION',
  SEND_PASSWORD_RESET: 'SEND_PASSWORD_RESET',

  // // Job Types - Webhooks
  // PROCESS_PAYSTACK_WEBHOOK: 'PROCESS_PAYSTACK_WEBHOOK',
  // PROCESS_FLUTTERWAVE_WEBHOOK: 'PROCESS_FLUTTERWAVE_WEBHOOK',
};
